### ISSUE TITLE
User blog page only showing 20 posts

### ISSUE THREAD

**Issue by kharoof** [eSteemApp/esteem#34]
Using esteem 1.3.5 on android when I navigate to the my home page and click on blog I can only navigate down through 20 posts. Its not showing all or it doesnt refresh as I scroll down.

**Comment by feruzm** [comment]
Thank you! This feature is in process and will be added 1.3.6

**Comment by feruzm** [comment]
should be fixed since v1.3.7, please feel free to comment or reopen

**Comment by kharoof** [comment]
This issue is still happening on V1.3.8. It shows less posts now initially, refreshes when I scroll down but only refreshes up to 20 posts.

**Comment by feruzm** [comment]
hmm, will reopen this and test further
